---
- name: Apply RHEL System Roles
  hosts: all
  become: true
  tasks:
  - name: Install RHEL/Fedora Web Console (Cockpit)
    include_role:
      name: redhat.rhel_system_roles.cockpit
    vars:
      cockpit_packages: default
  - name: Configure Firewall for Web Console
    include_role:
      name: redhat.rhel_system_roles.firewall
    vars:
      firewall:
        service: cockpit
        state: enabled
