---
- name: Demo RHEL system roles
  hosts: all
  become: true
  tasks:
  - name: Configure journald
    include_role:
      name: redhat.rhel_system_roles.journald
    vars:
      journald_persistent: true
      journald_max_disk_size: 2048
      journald_per_user: true
      journald_sync_interval: 1
